language: node_js
arch:
   - amd64
   - ppc64le
cache: yarn
node_js:
  - "node"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
before_install:
  - npm config set strict-ssl false
  - npm config set registry="http://registry.npmjs.org/"
